<a href="https://colab.research.google.com/github/rajasainikhil7-maker/eda/blob/main/numpy_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)


[10 20 30 40 50]
1
(5,)
int64
5


In [17]:
import numpy as np
arr=np.arange(1,13).reshape(3,4)
print(arr)

arr1=np.arange(1,25).reshape(2,3,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [23]:
import numpy as np
arr=np.zeros(2)
print(arr)

arr1=np.zeros((2,3))
print(arr1)

arr2=np.zeros((2,3,4))
print(arr2)


[0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [27]:
import numpy as np
arr=np.ones((2,3))
print(arr)
print(arr.shape)
print(arr.ndim)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
2


In [42]:
import numpy as np
arr=np.eye(5)
print(arr)

arr1=np.ones((4,4))
print(arr1)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [45]:
import numpy as np
arr=np.random.random(5)
print(arr)

arr1=np.random.random(6).reshape(2,3)
print(arr1)




[0.70596507 0.94236477 0.01760993 0.63419755 0.80080379]
[[0.83100287 0.72385418 0.47629838]
 [0.93918773 0.01957296 0.67835064]]


In [76]:
import numpy as np   #7
arr=np.random.uniform((10,50),3)
print(arr)



[ 9.63597708 39.26965816]


In [85]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,4) #14
print(arr)
result=np.ravel(arr)
print(result)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [86]:
import numpy as np  #13
arr = np.linspace(0, 100, 6)
print(arr)

[  0.  20.  40.  60.  80. 100.]


In [88]:
import numpy as np # 15

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)
print(arr.T)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [93]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)
arr = arr.astype(float)
print(arr)


[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [94]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)


[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [104]:
import numpy as np
marks=np.array([45,56,67,72,81,90,95])
print(marks)
print(np.var(marks))
print(np.std(marks))
print(np.argmax(marks))
print(np.argmin(marks))
print(np.log10(marks))
print(np.percentile(marks,25))
print(np.percentile(marks,75))



[45 56 67 72 81 90 95]
277.63265306122446
16.662312356369522
6
0
[1.65321251 1.74818803 1.8260748  1.8573325  1.90848502 1.95424251
 1.97772361]
61.5
85.5


In [119]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print(np.split(a,3))
print(np.split(b,3))
print(np.split(c,3))


[array([1]), array([2]), array([3])]
[array([4]), array([5]), array([6])]
[array([7]), array([8]), array([9])]
